"""add is_primary to product images

Revision ID: 2d99756865cf
Revises: fc3e1a432d1d
Create Date: 2026-06-23 14:50:56.265458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d99756865cf'
down_revision: Union[str, Sequence[str], None] = 'fc3e1a432d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('is_primary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'is_primary')
    # ### end Alembic commands ###
