"""empty message

Revision ID: d7a2312f0402
Revises: 426938f15b26
Create Date: 2026-07-14 14:39:04.357399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a2312f0402'
down_revision: Union[str, Sequence[str], None] = '426938f15b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=False))
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_cart_user_product_size'), 'cart_items', type_='unique')
    op.create_unique_constraint('uq_cart_product', 'cart_items', ['cart_id', 'product_id'])
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'user_id')
    op.drop_column('cart_items', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_constraint('uq_cart_product', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('uq_cart_user_product_size'), 'cart_items', ['user_id', 'product_id', 'size'], postgresql_nulls_not_distinct=False)
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'created_at')
    op.drop_column('cart_items', 'cart_id')
    op.drop_table('carts')
    # ### end Alembic commands ###
